name: Deploy
run-name: ${{ github.actor }} is running Deployment🚀

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            cd ~/fastapi-book-project
            git checkout main
            git pull origin main
            docker-compose down
            docker system prune -af
            docker-compose up -d --build
